In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('~/Dev/notebook/EURUSD1.csv', index_col='Date', parse_dates=True)

In [4]:
data

                        Open     High      Low    Close  Volume
Date
2015-12-16 11:25:00  1.07180  1.07213  1.07179  1.07205      98
2015-12-16 11:26:00  1.07205  1.07220  1.07183  1.07187      71
2015-12-16 11:27:00  1.07187  1.07197  1.07187  1.07197      49
2015-12-16 11:28:00  1.07195  1.07228  1.07195  1.07206     103
2015-12-16 11:29:00  1.07205  1.07232  1.07198  1.07218     114
2015-12-16 11:30:00  1.07217  1.07234  1.07216  1.07220      92
2015-12-16 11:31:00  1.07220  1.07234  1.07217  1.07225      83
2015-12-16 11:32:00  1.07226  1.07247  1.07225  1.07245      81
2015-12-16 11:33:00  1.07246  1.07266  1.07236  1.07259     119
2015-12-16 11:34:00  1.07260  1.07284  1.07260  1.07275      53
2015-12-16 11:35:00  1.07276  1.07295  1.07274  1.07286      69
2015-12-16 11:36:00  1.07288  1.07288  1.07275  1.07282      38
2015-12-16 11:37:00  1.07282  1.07285  1.07254  1.07257      79
2015-12-16 11:38:00  1.07258  1.07281  1.07258  1.07279      62
2015-12-16 11:39:00  1.07279  1.07279  1.07254  1.07260      91
2015-12-16 11:40:00  1.07257  1.07257  1.07242  1.07242      70
2015-12-16 11:41:00  1.07241  1.07242  1.07228  1.07234      82
2015-12-16 11:42:00  1.07234  1.07239  1.07228  1.07228      77
2015-12-16 11:43:00  1.07230  1.07256  1.07229  1.07241      48
2015-12-16 11:44:00  1.07241  1.07247  1.07224  1.07230      79
2015-12-16 11:45:00  1.07230  1.07246  1.07225  1.07243      62
2015-12-16 11:46:00  1.07244  1.07245  1.07229  1.07231      59
2015-12-16 11:47:00  1.07231  1.07234  1.07215  1.07215      51
2015-12-16 11:48:00  1.07215  1.07215  1.07185  1.07214      84
2015-12-16 11:49:00  1.07213  1.07225  1.07207  1.07225      46
2015-12-16 11:50:00  1.07226  1.07231  1.07182  1.07195      66
2015-12-16 11:51:00  1.07195  1.07198  1.07180  1.07184      77
2015-12-16 11:52:00  1.07185  1.07193  1.07169  1.07186      90
2015-12-16 11:53:00  1.07187  1.07211  1.07187  1.07199      78
2015-12-16 11:54:00  1.07198  1.07198  1.07187  1.07189      47
...                      ...      ...      ...      ...     ...
2016-12-22 21:48:00  1.17532  1.17543  1.17530  1.17543      23
2016-12-22 21:49:00  1.17542  1.17544  1.17535  1.17537      18
2016-12-22 21:50:00  1.17534  1.17534  1.17528  1.17532      16
2016-12-22 21:51:00  1.17531  1.17535  1.17521  1.17534      26
2016-12-22 21:52:00  1.17534  1.17540  1.17534  1.17540       6
2016-12-22 21:53:00  1.17539  1.17543  1.17532  1.17532      16
2016-12-22 21:54:00  1.17531  1.17531  1.17524  1.17524      22
2016-12-22 21:55:00  1.17524  1.17524  1.17520  1.17520      20
2016-12-22 21:56:00  1.17521  1.17533  1.17521  1.17529      30
2016-12-22 21:57:00  1.17529  1.17534  1.17522  1.17522      32
2016-12-22 21:58:00  1.17523  1.17523  1.17519  1.17520      31
2016-12-22 21:59:00  1.17521  1.17523  1.17513  1.17513      43
2016-12-22 22:00:00  1.17512  1.17517  1.17503  1.17513      39
2016-12-22 22:01:00  1.17513  1.17513  1.17502  1.17504      18
2016-12-22 22:02:00  1.17504  1.17513  1.17504  1.17513      14
2016-12-22 22:03:00  1.17514  1.17533  1.17514  1.17532      33
2016-12-22 22:04:00  1.17531  1.17536  1.17529  1.17533      18
2016-12-22 22:05:00  1.17534  1.17539  1.17529  1.17529      24
2016-12-22 22:06:00  1.17529  1.17533  1.17528  1.17528      10
2016-12-22 22:07:00  1.17530  1.17530  1.17519  1.17519      11
2016-12-22 22:08:00  1.17518  1.17531  1.17518  1.17523      23
2016-12-22 22:09:00  1.17524  1.17529  1.17522  1.17523      26
2016-12-22 22:10:00  1.17522  1.17528  1.17512  1.17513      29
2016-12-22 22:11:00  1.17514  1.17518  1.17514  1.17517       6
2016-12-22 22:12:00  1.17515  1.17517  1.17512  1.17516      11
2016-12-22 22:13:00  1.17517  1.17528  1.17517  1.17518      24
2016-12-22 22:14:00  1.17516  1.17516  1.17511  1.17511      16
2016-12-22 22:15:00  1.17509  1.17509  1.17504  1.17507      20
2016-12-22 22:16:00  1.17508  1.17509  1.17499  1.17502      23
2016-12-22 22:17:00  1.17499  1.17502  1.17499  1.17502      34

[67765 rows x 5 columns]